<?php
	$title = 'Delete Album';
	$this->headTitle($title);
?>

<h1><?php echo $this->escapeHTML($title); ?></h1>

<p>
	Are you sure you want to delete '<?php echo $this->escapeHTML($album->title); ?>' by '<?php echo $this->escapeHTML($album->artist)?>'?
</p>

<?php 
	$url = $this->url('album',
					  array('action' => 'delete',
							'id'	 => $this->id
						   )
					 );
?>

<form action="<?php echo $url?>" method="post">
	<div>
		<input type="hidden" name="id"  value="<?php echo (int)$album->id; ?>" />
		<input type="submit" name="del" value="Yes" />
		<input type="submit" name="del" value="No" />
	</div>
</form>