<?php
	$title = 'Edit Album';
	$this->headtitle($title);
?>

<h1> <?php echo $this->escapeHTML($title); ?> </h1>

<?php 
	$form = $this->form;
	$form->setAttribute('action', $this->url('album', array('action' => 'edit',
															'id'	 => $this->id
														   )
											)
					   );
	
	$form->prepare();
	
	echo $this->form()->openTag($form);
	echo $this->formHidden($form->get('id'));
	echo "<div class='form-group'>";
	echo $this->formrow($form->get('title')->setAttribute('class', 'form-control'));
	echo "</div>";
	echo "<div class='form-group'>";
	echo $this->formrow($form->get('artist')->setAttribute('class', 'form-control'));
	echo "</div>";
	echo "<div class='btn-group'>";
	echo $this->formSubmit($form->get('submit'));
	echo "</div>";
	echo $this->form()->closeTag();
?>